# permissions for end users to view suricata.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: suricata-viewer-role
rules:
- apiGroups:
  - managed.openshift.io
  resources:
  - suricata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - managed.openshift.io
  resources:
  - suricatas/status
  verbs:
  - get
